[build-system]
requires = ["hatchling>=1.24.0"]
build-backend = "hatchling.build"

[project]
name = "skripts-schemas"
version = "0.1.0"
description = "Shared schemas package"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[project.scripts]
skripts-schemas = "schemas.main:run"

[tool.hatch.build.targets.wheel]
packages = ["schemas"]
