[build-system]
requires = ["hatchling>=1.24.0"]
build-backend = "hatchling.build"

[project]
name = "skripts-eval"
version = "0.1.0"
description = "Evaluation package"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[project.scripts]
skripts-eval = "eval.main:run"

[tool.hatch.build.targets.wheel]
packages = ["eval"]
